# careerBoards.py — Company slug/token registry for job-search.py
# ─────────────────────────────────────────────────────────────────
# Add new companies here, or use:
#   python3 job-search.py add <board> <slug> <name>

# Greenhouse board tokens  →  display name
GREENHOUSE = {
    "anthropic":                            "Anthropic",
    "openai":                               "OpenAI",
    "perplexityai":                         "Perplexity",
    "reddit":                               "Reddit",
    "strava":                               "Strava",
    "mercury":                              "Mercury",
    "gusto":                                "Gusto",
    "headway":                              "Headway",
    "assemblyai":                           "AssemblyAI",
    "automatticcareers":                    "Automattic",
    "tailscale":                            "Tailscale",
    "heygen":                               "HeyGen",
    "speechify":                            "Speechify",
    "lumalabs":                             "Luma AI",
    "earnin":                               "EarnIn",
    "myfitnesspal":                         "MyFitnessPal",
    "faire":                                "Faire",
    "touchbistro":                          "TouchBistro",
    "warp":                                 "Warp",
    "notion":                               "Notion",
    "figma":                                "Figma",
    "xai":                                  "xAI",
    "remotecom":                            "Remote",
    "thenewyorktimes":                      "The New York Times",
    "boulevard":                            "Boulevard",
    "doordashusa":                          "DoorDash USA",
    "canonical":                            "Canonical",
    "gitlab":                               "GitLab",
    "thetradedesk":                         "The Trade Desk",
    "evio":                                 "Evio",
    "mlbevents":                            "MLB",
    "hpsinvestmentpartners":                "HPS Investment Partners",
    "pretiuminternships2025":               "Pretium",
    "breezeairways":                        "Breeze Airways",
    "impact":                               "Impact.com",
    "remotereferralboardinternaluseonly":   "Remote - Referral Board",
    "internaljobsatlush":                   "Lush",
    "remotepeople":                         "Remote People",
}

# Lever company slugs  →  display name
LEVER = {
    "wealthsimple":         "Wealthsimple",
    "lime":                 "Lime",
    "januaryinc":           "January AI",
    "vts":                  "VTS",
    "revi":                 "Revi",
    "ro":                   "Ro",
    "dnb":                  "Dun & Bradstreet",
    "truv":                 "Truv",
    "verifiable":           "Verifiable",
    "doola":                "Doola",
    "jumpcloud":            "JumpCloud",
    "rws":                  "RWS",
    "binance":              "Binance",
    "ion":                  "ION Group",
    "appen":                "Appen / CrowdGen",
    "livechatinc":          "Text",
    "gohighlevel":          "HighLevel",
    "palantir":             "Palantir",
    "permitflow":           "PermitFlow",
    "the-global-talent-co": "The Global Talent Co.",
}

# Ashby organisation slugs  →  display name
ASHBY = {
    "perplexity":               "Perplexity",
    "ramp":                     "Ramp",
    "linear":                   "Linear",
    "sentry":                   "Sentry",
    "cohere":                   "Cohere",
    "ideogram":                 "Ideogram",
    "sesame":                   "Sesame AI",
    "speak":                    "Speak",
    "revenuecat":               "RevenueCat",
    "pika":                     "Pika",
    "elevenlabs":               "ElevenLabs",
    "rogo":                     "Rogo",
    "suno":                     "Suno",
    "whatnot":                  "Whatnot",
    "bankjoy":                  "Bankjoy",
    "copilot-money":            "Copilot Money",
    "groundnews":               "Ground News",
    "wealthsimple":             "Wealthsimple",
    "lime":                     "Lime",
    "mem0":                     "Mem0",
    "writer":                   "Writer",
    "gradient":                 "Gradient",
    "nord-security":            "Nord Security",
    "bevel":                    "Bevel",
    "pocket-prep":              "Pocket Prep",
    "notable":                  "Notable",
    "renuity":                  "Renuity",
    "clipboard":                "Clipboard",
    "northslope-technologies":  "Northslope Technologies",
    "doss":                     "DOSS",
    "reedsy":                   "Reedsy",
    "verto":                    "Verto",
    "browsercompany":           "The Browser Company",
    "nomic":                    "Nomic",
    "stream":                   "Stream",
    "foundry-for-good":         "Foundry for Good",
    "new-story":                "New Story",
    "shortstory":               "Short Story",
    "abridge":                  "Abridge",
    "known":                    "Known",
    "replit":                   "Replit",
    "li.fi":                    "LI.FI",
    "dust":                     "Dust",
    "orb":                      "Orb",
    "eliseai":                  "EliseAI",
    "namespace":                "Namespace",
    "base":                     "Base",
    "ashby":                    "Ashby",
    "1password":                 "1Password",
    "9fin":                      "9Fin",
    "Acorns":                    "Acorns",
    "Adtucon":                   "Adtucon",
    "AlephAlpha":                "Alephalpha",
    "Anon":                      "Anon",
    "BranchInsurance":           "Branchinsurance",
    "Cambly":                    "Cambly",
    "Crusoe":                    "Crusoe",
    "CylinderHealth":            "Cylinderhealth",
    "DatologyAI":                "Datologyai",
    "Deel":                      "Deel",
    "DeepL":                     "Deepl",
    "Deepgram":                  "Deepgram",
    "Distyl":                    "Distyl",
    "FURTHER":                   "Further",
    "FlutterFlow":               "Flutterflow",
    "Fourier":                   "Fourier",
    "GPTZero":                   "Gptzero",
    "GoHenry":                   "Gohenry",
    "InscribeAI":                "Inscribeai",
    "Juicebox":                  "Juicebox",
    "LeanTech":                  "Leantech",
    "OpenSea":                   "Opensea",
    "Parkade":                   "Parkade",
    "Roam":                      "Roam",
    "Siro":                      "Siro",
    "Sonio":                     "Sonio",
    "Speakeasy":                 "Speakeasy",
    "StandardBots":              "Standardbots",
    "Stepful":                   "Stepful",
    "Tabs":                      "Tabs",
    "The-Flex":                  "The Flex",
    "aescape":                   "Aescape",
    "airapps":                   "Airapps",
    "airwallex":                 "Airwallex",
    "alan":                      "Alan",
    "almedia":                   "Almedia",
    "altimate":                  "Altimate",
    "altura":                    "Altura",
    "anglehealth":               "Anglehealth",
    "anima":                     "Anima",
    "ankorstore":                "Ankorstore",
    "anrok":                     "Anrok",
    "apify":                     "Apify",
    "aptosfoundation":           "Aptosfoundation",
    "arcade":                    "Arcade",
    "articul8":                  "Articul8",
    "artsy":                     "Artsy",
    "assembledhq":               "Assembledhq",
    "astera":                    "Astera",
    "atob":                      "Atob",
    "atroposhealth":             "Atroposhealth",
    "august-health":             "August Health",
    "axiom":                     "Axiom",
    "basis-ai":                  "Basis Ai",
    "beam":                      "Beam",
    "bedrockocean":              "Bedrockocean",
    "benepass":                  "Benepass",
    "bestow":                    "Bestow",
    "bettermile":                "Bettermile",
    "bifrost":                   "Bifrost",
    "blockhouse":                "Blockhouse",
    "blockworks":                "Blockworks",
    "blueberrypediatrics":       "Blueberrypediatrics",
    "boon":                      "Boon",
    "botanictonics":             "Botanictonics",
    "brainco":                   "Brainco",
    "brainly":                   "Brainly",
    "bratte":                    "Bratte",
    "brigit":                    "Brigit",
    "bunch":                     "Bunch",
    "cantina":                   "Cantina",
    "capimoney":                 "Capimoney",
    "carry":                     "Carry",
    "casca":                     "Casca",
    "centari":                   "Centari",
    "character":                 "Character",
    "chronospherejobs":          "Chronospherejobs",
    "cinder":                    "Cinder",
    "claylabs":                  "Claylabs",
    "cluely":                    "Cluely",
    "cointracker":               "Cointracker",
    "column":                    "Column",
    "comind":                    "Comind",
    "compa":                     "Compa",
    "comulate":                  "Comulate",
    "comun":                     "Comun",
    "corti":                     "Corti",
    "counsel":                   "Counsel",
    "count":                     "Count",
    "credal":                    "Credal",
    "dakota":                    "Dakota",
    "dandy":                     "Dandy",
    "dave":                      "Dave",
    "davidenergy":               "Davidenergy",
    "decagon":                   "Decagon",
    "deductive":                 "Deductive",
    "deel":                      "Deel",
    "deepwalk":                  "Deepwalk",
    "delian":                    "Delian",
    "devsavant":                 "Devsavant",
    "doppel":                    "Doppel",
    "earnedwealth":              "Earnedwealth",
    "ekumenlabs":                "Ekumenlabs",
    "ema":                       "Ema",
    "empora":                    "Empora",
    "endex":                     "Endex",
    "enode":                     "Enode",
    "equi":                      "Equi",
    "equip":                     "Equip",
    "everai":                    "Everai",
    "evertune":                  "Evertune",
    "fable":                     "Fable",
    "farmraise":                 "Farmraise",
    "feathr":                    "Feathr",
    "finalis":                   "Finalis",
    "finary":                    "Finary",
    "finch":                     "Finch",
    "finvest":                   "Finvest",
    "fleetpulse":                "Fleetpulse",
    "freshpaint":                "Freshpaint",
    "fullstory":                 "Fullstory",
    "g2i":                       "G2I",
    "handshake":                 "Handshake",
    "handspring":                "Handspring",
    "harvey":                    "Harvey",
    "hawk":                      "Hawk",
    "hcompany":                  "Hcompany",
    "heyjobs":                   "Heyjobs",
    "hiive":                     "Hiive",
    "hims-and-hers":             "Hims And Hers",
    "horizon3ai":                "Horizon3Ai",
    "hotplate":                  "Hotplate",
    "humaans":                   "Humaans",
    "immersivelabs":             "Immersivelabs",
    "improbable":                "Improbable",
    "invert":                    "Invert",
    "january":                   "January",
    "jigsaw":                    "Jigsaw",
    "join9am":                   "Join9Am",
    "joko":                      "Joko",
    "julius":                    "Julius",
    "junipersquare":             "Junipersquare",
    "keyrock":                   "Keyrock",
    "kindred":                   "Kindred",
    "kovo":                      "Kovo",
    "kraken.com":                "Kraken.Com",
    "krea":                      "Krea",
    "kustomer":                  "Kustomer",
    "latitude":                  "Latitude",
    "leland":                    "Leland",
    "letta":                     "Letta",
    "lightning":                 "Lightning",
    "lightspark":                "Lightspark",
    "limble":                    "Limble",
    "lindushealth":              "Lindushealth",
    "listenlabs":                "Listenlabs",
    "liveflow":                  "Liveflow",
    "lucidlink":                 "Lucidlink",
    "lunar":                     "Lunar",
    "mach":                      "Mach",
    "mach9":                     "Mach9",
    "magiceden":                 "Magiceden",
    "magicschool":               "Magicschool",
    "mandolin":                  "Mandolin",
    "mangomint":                 "Mangomint",
    "masabi":                    "Masabi",
    "mazehq":                    "Mazehq",
    "menlosecurity":             "Menlosecurity",
    "metalenz":                  "Metalenz",
    "middesk":                   "Middesk",
    "mintlify":                  "Mintlify",
    "modernfi":                  "Modernfi",
    "moderntreasury":            "Moderntreasury",
    "moego":                     "Moego",
    "monarchmoney":              "Monarchmoney",
    "mondoo":                    "Mondoo",
    "montecarlodata":            "Montecarlodata",
    "mosey":                     "Mosey",
    "mystenlabs":                "Mystenlabs",
    "n8n":                       "N8N",
    "netboxlabs":                "Netboxlabs",
    "netic":                     "Netic",
    "neworbit":                  "Neworbit",
    "niramedical":               "Niramedical",
    "numeric":                   "Numeric",
    "olive":                     "Olive",
    "omnea":                     "Omnea",
    "omniscient":                "Omniscient",
    "oneapp":                    "Oneapp",
    "onebrief":                  "Onebrief",
    "openai":                    "Openai",
    "opengov":                   "Opengov",
    "oplabs":                    "Oplabs",
    "opusclip":                  "Opusclip",
    "oumi":                      "Oumi",
    "parabola-io":               "Parabola Io",
    "parallel":                  "Parallel",
    "partiful":                  "Partiful",
    "partisiablockchain":        "Partisiablockchain",
    "passage":                   "Passage",
    "patreon":                   "Patreon",
    "peek":                      "Peek",
    "phylax":                    "Phylax",
    "plain":                     "Plain",
    "plasmidsaurus":             "Plasmidsaurus",
    "polygon-labs":              "Polygon Labs",
    "posthog":                   "Posthog",
    "primer":                    "Primer",
    "proofofplay":               "Proofofplay",
    "propelus":                  "Propelus",
    "protege":                   "Protege",
    "pylon-labs":                "Pylon Labs",
    "quicknode":                 "Quicknode",
    "raiku":                     "Raiku",
    "ravio":                     "Ravio",
    "reddit":                    "Reddit",
    "reflectionai":              "Reflectionai",
    "reka":                      "Reka",
    "remberg":                   "Remberg",
    "replo":                     "Replo",
    "rilla":                     "Rilla",
    "rocketsciencegg":           "Rocketsciencegg",
    "rula":                      "Rula",
    "sardine":                   "Sardine",
    "scaler":                    "Scaler",
    "scrollmark":                "Scrollmark",
    "seconddinner":              "Seconddinner",
    "sensmore":                  "Sensmore",
    "sentilink":                 "Sentilink",
    "siena":                     "Siena",
    "silver":                    "Silver",
    "skydropx":                  "Skydropx",
    "sleeper":                   "Sleeper",
    "slingshotai":               "Slingshotai",
    "slope":                     "Slope",
    "smalls":                    "Smalls",
    "solace":                    "Solace",
    "sona":                      "Sona",
    "sprig":                     "Sprig",
    "stainlessapi":              "Stainlessapi",
    "statsig":                   "Statsig",
    "stealthventurecapitalfirm": "Stealthventurecapitalfirm",
    "stedi":                     "Stedi",
    "stickermule":               "Stickermule",
    "supabase":                  "Supabase",
    "superdial":                 "Superdial",
    "superduper":                "Superduper",
    "suzy":                      "Suzy",
    "svix":                      "Svix",
    "symbiotic":                 "Symbiotic",
    "synthflow":                 "Synthflow",
    "talentful":                 "Talentful",
    "tandem":                    "Tandem",
    "tapcart":                   "Tapcart",
    "taptapsend":                "Taptapsend",
    "tarro":                     "Tarro",
    "tenex":                     "Tenex",
    "thatgamecompany":           "Thatgamecompany",
    "thirstysprout":             "Thirstysprout",
    "tonal":                     "Tonal",
    "traba":                     "Traba",
    "turnstile":                 "Turnstile",
    "twelve":                    "Twelve",
    "udisc":                     "Udisc",
    "uipath":                    "Uipath",
    "valeriehealth":             "Valeriehealth",
    "vanta":                     "Vanta",
    "vapi":                      "Vapi",
    "virtahealth":               "Virtahealth",
    "virtuous":                  "Virtuous",
    "vitalize":                  "Vitalize",
    "voladynamics":              "Voladynamics",
    "vooma":                     "Vooma",
    "warp":                      "Warp",
    "wayflyer":                  "Wayflyer",
    "weave":                     "Weave",
    "welltech":                  "Welltech",
    "winona":                    "Winona",
    "withclutch":                "Withclutch",
    "withpulley":                "Withpulley",
    "xbowcareers":               "Xbowcareers",
    "yondr":                     "Yondr",
    "yutori":                    "Yutori",
    "zapier":                    "Zapier",
    "zefir":                     "Zefir",
    "zefr":                      "Zefr",
    "zencastr":                  "Zencastr",
    "zyphra":                    "Zyphra",

    "acorns":          "Acorns",
    "adtucon":         "Adtucon",
    "alephalpha":      "Alephalpha",
    "anon":            "Anon",
    "branchinsurance": "Branchinsurance",
    "cambly":          "Cambly",
    "crusoe":          "Crusoe",
    "cylinderhealth":  "Cylinderhealth",
    "datologyai":      "Datologyai",
    "deepgram":        "Deepgram",
    "deepl":           "Deepl",
    "distyl":          "Distyl",
    "flutterflow":     "Flutterflow",
    "fourier":         "Fourier",
    "further":         "Further",
    "gohenry":         "Gohenry",
    "gptzero":         "Gptzero",
    "inscribeai":      "Inscribeai",
    "juicebox":        "Juicebox",
    "leantech":        "Leantech",
    "opensea":         "Opensea",
    "parkade":         "Parkade",
    "roam":            "Roam",
    "siro":            "Siro",
    "sonio":           "Sonio",
    "speakeasy":       "Speakeasy",
    "standardbots":    "Standardbots",
    "stepful":         "Stepful",
    "tabs":            "Tabs",
    "the-flex":        "The Flex",

}
